### ISSUE TITLE
I don't have response 

### ISSUE THREAD

**Issue by Khezo** [watson-developer-cloud/assistant-simple#163]
Hi,

I don't understand my error, i check credentials and it's ok, but i don't have response from watson.
Thanks !!!

```
_http_server.js:192
    throw new RangeError(`Invalid status code: ${statusCode}`);
    ^

RangeError: Invalid status code: 0
    at ServerResponse.writeHead (_http_server.js:192:11)
    at ServerResponse._implicitHeader (_http_server.js:157:8)
    at ServerResponse.OutgoingMessage.end (_http_outgoing.js:574:10)
    at ServerResponse.send (C:\Users\khalil.rachidi\Documents\Watson_Conversation\assistant-simple-master\assistant-simple-master\node_modules\express\lib\response.js:221:10)
    at ServerResponse.json (C:\Users\khalil.rachidi\Documents\Watson_Conversation\assistant-simple-master\assistant-simple-master\node_modules\express\lib\response.js:267:15)
    at C:\Users\khalil.rachidi\Documents\Watson_Conversation\assistant-simple-master\assistant-simple-master\app.js:58:42
    at Request._callback (C:\Users\khalil.rachidi\Documents\Watson_Conversation\assistant-simple-master\assistant-simple-master\node_modules\watson-developer-cloud\lib\requestwrapper.js:61:13)
    at self.callback (C:\Users\khalil.rachidi\Documents\Watson_Conversation\assistant-simple-master\assistant-simple-master\node_modules\watson-developer-cloud\node_modules\request\request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)

npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! assistant-simple@0.1.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the assistant-simple@0.1.1 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the assistant-simple package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs assistant-simple
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls assistant-simple
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\khalil.rachidi\Documents\Watson_Conversation\assistant-simple-master\assistant-simple-master\npm-debug.log
```

**Comment by Khezo** [comment]
it was a security problem, I didn't have some access. you can close the issue
 thank you very much
